graph TD
    V[Variável] --> Quant[Quantitativa]
    V --> Qual[Qualitativa]
    Quant --> Discreta[Discreta]
    Quant --> Continua[Contínua]
    Qual --> Nominais[Nominais]
    Qual --> Ordinais[Ordinais]
